//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stroitelstvo.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int IdFlat { get; set; }
        public string HouseNumber { get; set; }
        public string Number { get; set; }
        public string TotalArea { get; set; }
        public string LivingArea { get; set; }
        public string NumberOfRooms { get; set; }
        public string Cost { get; set; }
        public int IdStatus { get; set; }
        public int IdJK { get; set; }
    
        public virtual JK JK { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
