//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stroitelstvo.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IdSale { get; set; }
        public int IdFlat { get; set; }
        public int IdStaff { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Flat Flat { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
